### ISSUE TITLE
Add support of macOS with ARM CPU

### ISSUE THREAD

**Issue by kelson42** [openzim/node-libzim#133]

**Comment by kelson42** [comment]
@audiodude Strongly supecting you are impacted by this?!

**Comment by audiodude** [comment]
Yes I've been unable to install mwoffliner on my Macbook, I've been doing development on my Linux desktop

**Comment by kelson42** [comment]
With latest `3.2.3` it seems to work now.

**Comment by maxwell-martin** [comment]
It does not work inside a Docker container using Linux OS on a MacBook Air with Apple Silicon:

**Correct file appears to be downloaded:**

npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim
npm ERR! command failed
npm ERR! command sh -c npm run download && node-gyp rebuild -v && npm run bundle
npm ERR! > @openzim/libzim@3.4.0 download
npm ERR! > node ./download-libzim.js
npm ERR! 
npm ERR! os.type() is: Linux
npm ERR! os.arch() is: arm64
**npm ERR! Downloading Libzim from:  https://download.openzim.org/release/libzim/libzim_linux-aarch64-manylinux-9.3.0.tar.gz**
npm ERR! Running Extract: [tar --strip-components 1 -xf ./download/libzim_linux-aarch64-manylinux-9.3.0.tar.gz -C ./download]
npm ERR! Successfully downloaded and extracted file

**Build script still looking for x86_64 libzim:**

npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
**npm ERR! /usr/bin/ld: cannot find /usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/lib/x86_64-linux-gnu/libzim.so.9: No such file or directory**
npm ERR! collect2: error: ld returned 1 exit status
npm ERR! make: *** [zim_binding.target.mk:139: Release/obj.target/zim_binding.node] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/mwoffliner/node_modules/node-gyp/lib/build.js:216:23)
npm ERR! gyp ERR! System Linux 6.10.14-linuxkit
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/mwoffliner/node_modules/.bin/node-gyp" "rebuild" "-v"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim
npm ERR! gyp ERR! node -v v20.19.2
npm ERR! gyp ERR! node-gyp -v v10.3.1
npm ERR! gyp ERR! not ok
