### ISSUE TITLE
Broken Travis Build

### ISSUE THREAD

**Issue by ISNIT0** [openzim/node-libzim#18]
I can't reproduce this issue on Mac (where the latest version of libzim is installed to the system).

I can, however reproduce in Docker using this Dockerfile:

```dockerfile
FROM node:8

RUN git clone https://github.com/openzim/node-libzim.git
RUN cd node-libzim &&\
    npm i &&\
    npm run install &&\
    npm run tsc
CMD cd node-libzim && npm t
```

You should see the error when running the built image

EDIT: I retried on my VPS, and I get the same error

**Comment by ISNIT0** [comment]
The only place I see this breaking is cases that the binary is downloaded from the CDN

**Comment by kelson42** [comment]
@mgautierfr @ISNIT0 I think this is the piece to read https://wiki.debian.org/GCC5#libstdc.2B-.2B-_ABI_transition

**Comment by ISNIT0** [comment]
The node-libzim travis file is `xenial` and `gcc-4.8` (tried `4.9` but it broke).

We also set `-D_GLIBCXX_USE_CXX11_ABI=0` https://github.com/openzim/node-libzim/blob/master/build/native/binding.gyp#L27
