### ISSUE TITLE
Favicon Redirect

### ISSUE THREAD

**Issue by ISNIT0** [openzim/node-libzim#20]
When calling the latest version of node-libzim from MWOffliner, I get a warning:
`Invalid redirection  redirecting to (missing) -Favicon`
It seems a slash is missing between the `-` and `Favicon`

The Favicon redirect code in node-libzim is here:
https://github.com/openzim/node-libzim/blob/master/src/ZimCreator.ts#L90
Which then calls here:
https://github.com/openzim/node-libzim/blob/master/src/Article.cc#L90

The redirect namespace works fine for other articles, so I'm not sure why this is happening.
Any ideas @mgautierfr ?

**Comment by kelson42** [comment]
@ISNIT0 I think you have fixed this?

**Comment by ISNIT0** [comment]
No, I believe it's an issue in in libzim

The same code behaves fine for all other articles, it's just the Favicon that seemingly doesn't get the slash in the redirect
