### ISSUE TITLE
Articles and `shouldIndex` method.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/node-libzim#30]
I'm not sure it is a bug. But I prefer to speak about it for nothing than be quite when I should speak :)

With the last change in libzim 6.0.0, the `shouldIndex` should also return `true` for redirect article if needed.
"If needed" means that if the user can search for the article (probably any html article, but not mandatory). Whatever if the article is a plain article or a redirect one.

**Comment by kelson42** [comment]
@ISNIT0 What @mgautierfr says sounds correct. Could we fix it? What is the current impact of not doing it properly?

**Comment by kelson42** [comment]
@mgautierfr Is that still an actual bug? Notnsure I fully understand it anymore.

**Comment by mgautierfr** [comment]
I don't know. Does node-libzim correctly return `true` for `shouldIndex` if the article has to be indexed ?

**Comment by kelson42** [comment]
@mgautierfr I don't know... but I don't have complained about the problem.

**Comment by kelson42** [comment]
@mgautierfr Does that mean MWoffliner works properly here? https://github.com/openzim/mwoffliner/blob/master/src/mwoffliner.lib.ts#L477

**Comment by mgautierfr** [comment]
It seems you always return `true` for redirect articles. If redirect articles are always article to be indexed you are good. Else, you should return true only if you want to index them.

**Comment by kelson42** [comment]
@mgautierfr Looks good to me.
