### ISSUE TITLE
Move to https://nodejs.org/api/n-api.html

### ISSUE THREAD

**Issue by kelson42** [openzim/node-libzim#31]
nbind is not supported and N-API seems mature/good enough

**Comment by kelvinhammond** [comment]
@kelson42 is this still an issue?

**Comment by kelson42** [comment]
@kelvinhammond Thank you very much again for this really important fix. @midik is currently working on a release of it which should be used in next MWoffliner minor release (in the next days). I have as well open a ticket to rearchitecture that binding in a way which is more respectful of libzim design, see #36.
