### ISSUE TITLE
Publish for macOS

### ISSUE THREAD

**Issue by kelson42** [openzim/node-libzim#32]
Currently we publish for GNU/Linux only.

**Comment by kelson42** [comment]
Depends on https://github.com/kiwix/kiwix-build/issues/349

**Comment by kelson42** [comment]
We have now the binaries for macOS published, see https://download.openzim.org/release/libzim/libzim_macos-x86_64-6.1.6.tar.gz for example

**Comment by bakshiutkarsha** [comment]
@kelson42 Yes it would be a good learning experience for me and would be beneficial to all JS contributors(for macOS). I can take up this ticket.
