### ISSUE TITLE
Unable to set main page + wrong mime types

### ISSUE THREAD

**Issue by midik** [openzim/node-libzim#38]
Tested with `mwoffliner 1.10.6` on `edutech` wiki.
Branch: `master`
Node: `10.16.x`

```
node -r ts-node/register src/cli.ts
--adminEmail=admin@kiwix.org
--mwUrl=https://edutechwiki.unige.ch/fr
--mwApiPath=../fmediawiki/api.php
--mwWikiPath=./
--mwModulePath=../fmediawiki/load.php
--articleList=./single.tsv
--useDownloadCache
--downloadCacheDirectory=cache
--speed=0.1
```

`single.tsv` content:
```
Instrumentation
Zim
Eonautes
```
### Results with 2.1.0 (works)
Zim file [2.1.0.zim.gz](https://github.com/openzim/node-libzim/files/4582047/2.1.0.zim.gz)

```
 mid@mid-arch  ~  _  k  m  o  compare   master…  ~/utils/zim-tools/zimdump -F 2.1.0.zim        
count-articles: 71
uuid: 7817c780-aaea-3e43-31ca-06c6cbd9463f
article count: 71
mime list pos: 80
url ptr pos: 197
title idx pos: 765
cluster count: 2
cluster ptr pos: 3947
checksum pos: 417386
checksum: 9bf23005cd9c0445dcc07f7520fcde73
main page: 47
layout page: -
```
![image](https://user-images.githubusercontent.com/6795530/81088856-3fb9be00-8f04-11ea-8cf1-fdbce852bac3.png)

```
3/33
T:12; A:69; RA:0; CA:35; UA:34; FA:0; IA:3; C:0; CC:0; UC:0; WC:0
text/plain=9;text/css=9;application/javascript=12;image/png=31;text/html=4;image/gif=2;image/jpeg=1
```

### Results with 2.1.1 (broken)
Zim file [2.1.1.zim.gz](https://github.com/openzim/node-libzim/files/4582055/2.1.1.zim.gz)
```
 mid@mid-arch  ~  _  k  m  o  compare   master…  ~/utils/zim-tools/zimdump -F 2.1.1.zim        
count-articles: 71
uuid: ad3d2ef3-0c95-feeb-a869-43680b5922c2
article count: 71
mime list pos: 80
url ptr pos: 415638
title idx pos: 416206
cluster count: 2
cluster ptr pos: 416490
checksum pos: 416506
checksum: bff12d73240fdeca86ab939a4d6c2a0e
main page: -
layout page: -
```

![image](https://user-images.githubusercontent.com/6795530/81088660-ee113380-8f03-11ea-90df-bddb5e789d76.png)

```
3/33
T:13; A:69; RA:0; CA:68; UA:1; FA:0; IA:3; C:0; CC:0; UC:0; WC:0
text/plain = 63;image/png = 1;text/html = 4
```

**Comment by midik** [comment]
upd: [mime types dump](https://github.com/openzim/node-libzim/files/4582144/mimeTypes-2.1.1.txt)  taken on 2.1.1 in `ZimCreator.addArticle()`

**Comment by midik** [comment]
more clues (2.1.0 vs 2.1.1)
![image](https://user-images.githubusercontent.com/6795530/81097779-0b003380-8f11-11ea-9169-85320bb508a8.png)

**Comment by kelson42** [comment]
@kelvinhammond Any idea?

**Comment by kelson42** [comment]
@mgautierfr I have a kind of suspission here this is related to the new way we save the ZIM header because both mainpage and mime-types are things stored in the ZIM header. An intuition here about the rootcause?

**Comment by midik** [comment]
as for typescript part, it seems like we call the binding methods with correct data (both main page and mime types).

**Comment by kelson42** [comment]
> as for typescript part, it seems like we call the binding methods with correct data (both main page and mime types).

@midik @kelson42 OK, if this clear I would wait the feedback of @mgautierfr on this before any further investigation.

**Comment by mgautierfr** [comment]
On the main page, there is a small change in the api with the last version.
`getMainUrl`, `getLayoutUrl` and `getUuid` have been set to `const`.
If you do not change it in the wrapper, you don't overwrite the method and libzim will the default implementation (no main page).

For the mimetype, I don't know. One thing for sure is that in the 2.1.1.zim file there is only `application/octet-stream+xapian`, `image/png`, `text/html` and `text/plain` mimetypes. So the problem is on the writing part, not the reading.

Can you give me the used version/tag of node-libzim, mwoffliner and libzim ?

**Comment by midik** [comment]
> Can you give me the used version/tag of node-libzim, mwoffliner and libzim ?

mwoffliner: [wpen-testing](https://github.com/openzim/mwoffliner/releases/tag/wpen-testing)
#### Works
node-libzim: [2.0.18](https://github.com/openzim/node-libzim/releases/tag/v2.0.18) - (I wrongly mentioned 2.1.0 above)
libzim: 6.0.0 (as defined in `.env`)
#### Broken
node-libzim: [this branch](https://github.com/openzim/node-libzim/tree/debugging-and-jest-coverage)
libzim: 6.1.1 (as defined in `.env`)

**Comment by mgautierfr** [comment]
The pb is in node-libzim.
In 2.0.8 (https://github.com/openzim/node-libzim/blob/v2.0.18/src/Article.ts#L43)
the mimetype is inferred from the url if it is not provided.
If `debugging-and-jest-coverage` branch (https://github.com/openzim/node-libzim/blob/debugging-and-jest-coverage/src/article.cc#L72-L74) "text/plain" is used if it is not provided.

As there is several place in mwoffliner where you not set the mimeType ([1](https://github.com/openzim/mwoffliner/blob/wpen-testing/src/util/dump.ts#L139), [2](https://github.com/openzim/mwoffliner/blob/wpen-testing/src/util/misc.ts#L165), [3](https://github.com/openzim/mwoffliner/blob/wpen-testing/src/util/saveArticles.ts#L52), [4](https://github.com/openzim/mwoffliner/blob/wpen-testing/src/mwoffliner.lib.ts#L394-L398)), node-libzim doesn't set the right mimetype.

**Comment by kelson42** [comment]
@mgautierfr Thank you
@midik If the mime-type is not set then the node-libzim should auto-detect it based on the "file" extension. But is you easily know it, would be better to tell it properly.

**Comment by midik** [comment]
> @midik If the mime-type is not set then the node-libzim should auto-detect it based on the "file" extension.

Well, auto-detection logic has been removed during n-api migration [here](https://github.com/openzim/node-libzim/commit/315fe35e9160f36f5a30fbf62dbbd10bfbe53e35) along with ZimArticle class. That's probably why mime-type used to set correctly before. Mwoffliner doesn't always provide mime-type while calling addArticle(), that's the way it's always been. I'll fix that. 
@mgautierfr thank you for your help.

**Comment by kelson42** [comment]
@midik This removal is an error. Considering that this logic is quite common to all scraper, I would try to avoid it to have it in MWoffliner.

**Comment by midik** [comment]
fixed: [edutechwiki_fr_single_2020-05.zim.gz](https://github.com/openzim/node-libzim/files/4591877/edutechwiki_fr_single_2020-05.zim.gz)
@kelson42 please review the PR

**Comment by midik** [comment]
btw confirmed that it works on node v14.2.0 (that gonna become LTS later this year)

**Comment by midik** [comment]
Metadata comparison
![image](https://user-images.githubusercontent.com/6795530/81279338-abfd0480-905f-11ea-9a88-3c65c4f4b6ff.png)

Fileinfo comparison
![image](https://user-images.githubusercontent.com/6795530/81279650-16ae4000-9060-11ea-8182-0fe0fd724c26.png)
