### ISSUE TITLE
New synchronisation bug?

### ISSUE THREAD

**Issue by kelson42** [openzim/node-libzim#41]
If I just do that:
```
$ git diff .
diff --git i/test/zim.test.ts w/test/zim.test.ts
index cf720aa..fa72054 100644
--- i/test/zim.test.ts
+++ w/test/zim.test.ts
@@ -58,6 +58,13 @@ describe('ZimCreator', () => {
     await creator.addArticle(new ZimArticle({ns: 'I', data: 'image test', url: 'image_test', mimeType: 'image/png'}));
     await creator.addArticle(new ZimArticle({ns: '-', data: 'common namespace test', url: 'common_namespace_test'}));
 
+    function sleep() {
+       return new Promise((resolve) => {
+          setTimeout(resolve, 5000);
+       });
+     };
+    await sleep();
+
     await creator.finalise();
   });
 
```

Which means just waiting 5 s. before finishing the ZIM files, then I get a crash in the libzim:
```
$ npm run test

> @openzim/libzim@2.2.1 test /home/kelson/code/node-libzim
> jest


 RUNS  test/zim.test.ts
terminate called after throwing an instance of 'std::runtime_error'
  what():  error 2 opening file "/home/kelson/code/node-libzim/test.zim
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @openzim/libzim@2.2.1 test: `jest`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the @openzim/libzim@2.2.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kelson/.npm/_logs/2020-05-13T09_04_35_294Z-debug.log
```

But if I wait 4900 ms. instead of 4 s. then it pass.

That looks really like a bug, we should be able to wait as long as needed and continue without any problem.

**Comment by mgautierfr** [comment]
This may be related to https://github.com/openzim/libzim/issues/333.
I cannot reproduce with a libzim compiled on my computer.
Using a release build have a issue (but not the same, the zim file is 0 byte)

**Comment by mgautierfr** [comment]
I'm not a node expert (at all) and I don't know what you path does exactly.

But if I add a `console.log("after sleep");` just after the `await sleep()`, it is never called. If a comment the `await sleep()`, the log is printed.

I have think about a test timeout stopping the test before it finish. The default timeout is 5000 (https://jestjs.io/docs/en/cli#--testtimeoutnumber), but running the test with `npm test --verbose --testTimeout=10000 test/zim.test.ts` doesn't help.

**Comment by kelson42** [comment]
@midik Your expertise is needed here I guess.

**Comment by midik** [comment]
This is not a pb with node-libzim but with a test timeout. So @mgautierfr you're looking at the right direction ;) Default timeout for jest is 5000 ms, and we have two options to override it:
- per-module: using `jest.setTimeout(10000);` directly in a test module, after `import` block;
- globally by passing `--testTimeout` parameter. Just only point is how we need to pass it.

This way we pass the parameter to `npm`:
```
npm test --testTimeout=...
````
This one we pass it to `jest`:
```
npm test -- --testTimeout=...
```
@kelson42 so `npm run test -- --testTimeout=10000` do the trick.

**Comment by kelson42** [comment]
@mgautierfr @midik So sorry about the wrong bug report :(
