### ISSUE TITLE
Clarify CI

### ISSUE THREAD

**Issue by rgaudin** [openzim/node-libzim#45]
The CI runs twice on a matrix over a `$PLATFORM` environ (either `native_static` or `native_dyn`) which is apparently not used.

publish.sh mentions it to trigger the publication only once:

https://github.com/openzim/node-libzim/blob/d635e150454b87e97b7cc60ac1c6f51e23cc41cf/dev/publish.sh#L2

So either this is a CI issue (looks copied over from kiwix-build) and we're running tests twice for nothing or this should be better documented.

**Comment by rgaudin** [comment]
I guess the CI should be migrated to github actions also…

**Comment by kelson42** [comment]
@MananJethwani is working on migrating the CI to actions.
