### ISSUE TITLE
Reduce number of Travis targets

### ISSUE THREAD

**Issue by ISNIT0** [openzim/node-libzim#5]
The last set of Travis build tasks took over two and a half hours to complete.
We're testing quite a few old versions of Node and ioJS which are in little use now.

I think we could get a way with the last 3 versions of NodeJS.

Thoughts?
@cscott 
@kelson42

**Comment by ISNIT0** [comment]
I have made these changes in #3

**Comment by kelson42** [comment]
@ISNIT0 Sounds reasonable to me, the most recent one and the LTS sounds good enough to me.

**Comment by ISNIT0** [comment]
Okay, I'll set it up for:
- Latest (10+)
- LTS (8.12.0)
