### ISSUE TITLE
can't install on OSX

### ISSUE THREAD

**Issue by eranhr** [openzim/node-libzim#50]
Trying to install libzim on mac but with no success. Tried to follow "On MacOS you'll need to install libzim separately ([see here](https://github.com/openzim/libzim/))." but also didn't succeed. Any assistance / guidance will be appreciated.

My goal is to read ZIM files (from JS/nodejs) into my DB.

**Comment by kelson42** [comment]
Installing from npmjs.org should just make it, the README is outdated. Please secure you don't have installed it manually and just install `node-libzim` via npm.

**Comment by kelson42** [comment]
README.md fixed.

**Comment by kelson42** [comment]
@eranhr Closing the issue please open a new ticket if you still have a problem with standard npm install process.
