### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by kelvinhammond** [openzim/node-libzim#83]
- [x] Secure the CI is green on git `master`
- [x] Update the Changelog
- [x] Update version
- [x] Create a tag on git
- [x] Secure new version is published on https://www.npmjs.com/package/openzim/libzim
- [x] Update the Github release with the Changelog
- [ ] Create new empty entry in Changelog (placeholder for future entries)
- [ ] Close current milestone and create new one incrementaly (_a priori_ a minor version)
- [ ] Advertise this new version

The version of libzim on the releases page on github and on npm do not match the current version of node-libzim in master.

**Comment by kelson42** [comment]
I’m not confortable to release as soon as #80 is not fixed. It’s a regression and MWoffliner will be stringly impacted. Right?

**Comment by kelvinhammond** [comment]
Probably, not sure how we'll fix that, I'll run the test suite later and see just how bad it is.
