### ISSUE TITLE
Apple Silicon configuration bug.

### ISSUE THREAD

**Issue by FledgeXu** [openzim/node-libzim#92]
Relative to: https://github.com/openzim/libzim/issues/764, https://github.com/openzim/mwoffliner/issues/1793
For now, `node-libzim` will only download the `macos-x86_64` package. But we can not fix this now, because `libzim` does not supported `macos-arm64` yet.
https://github.com/openzim/node-libzim/blob/b5b717a0c3cc908420fc49860c2d626aa1c42d1c/download-libzim.js#L18-L21

**Comment by kelson42** [comment]
Depends on https://github.com/openzim/libzim/issues/753
